---
# tasks file for update_tower_license

- name: Post license key
  uri:
    url: https://{{ansible_host}}/api/v2/config/
    method: POST
    user: "{{ local_account_username }}"
    password: "{{ local_account_password }}"
    body: "{{ tower_license }}"
    body_format: json
    validate_certs: false
    force_basic_auth: yes
    status_code:
      - 200
  delegate_to: localhost
