---
# tasks file for update_tower_license
#
- debug:
    msg: "{{ playbook_dir }}"

- name: auto license feature for Ansible Tower
  block:
    - name: Check that the provided license exists
      stat:
        path: "{{ playbook_dir }}/tower_license.json"
      register: stat_result
    - debug:
        var: stat_result
    - fail:
        msg: "We need a license located at {{ playbook_dir }}/tower_license.json"
      when:
        - not stat_result.stat.exists

- name: Ensure eula is accepted if posting license
  command: python -c "import json; license = json.loads(open('{{playbook_dir}}/tower_license.json', 'r').read()); ceula = license.get('eula_accepted'); license['eula_accepted'] = True if not ceula else ceula ; open('{{playbook_dir}}/tower_license.json', 'w').write(json.dumps(license));"
  delegate_to: localhost
  run_once: true
  become: false

- name: Post license key
  uri:
    url: https://{{ansible_host}}/api/v2/config/
    method: POST
    user: admin
    password: "{{admin_password}}"
    body: "{{ lookup('file',playbook_dir+'/tower_license.json') }}"
    body_format: json
    validate_certs: false
    force_basic_auth: true
